dataset_path: "/opt/ml/input/data"

checkpoint_dir: .ckpts
seed: 12405

akt_config: # not used
  embedding_size: 64
  num_blocks: 2
  kq_same: True
  model_type: "akt"
  num_attn_heads: 8
  final_fc_dim: 512
  d_ff: 1024
  l2: 0.0
  dropout: 0.05
  separate_qr: False
  
cl4kt_config:
  hidden_size: 64
  num_blocks: 2
  num_attn_heads: 8
  kq_same: True
  final_fc_dim: 512
  d_ff: 1024
  l2: 0.0 # no effect
  dropout: 0.2 # no effect
  reg_cl: 0.1 # no effect
  mask_prob: 0.5 # no effect
  crop_prob: 0.5 # no effect
  permute_prob: 0.5 # no effect
  replace_prob: 0.5 # no effect
  negative_prob: 1.0 # no effect
  temp: 0.05
  hard_negative_weight: 1.0


train_config:
  log_wandb_fold: True
  sequence_option: "recent" # early or recent
  seq_len: 100 
  batch_size: 64 # no effect
  eval_batch_size: 64 
  num_epochs: 300
  print_epochs: 1
  max_grad_norm: 2.0
  learning_rate: 0.001 # no effect
  optimizer: adam # no effect
  
  loss: BCE

  ## Model Save
  save_model: False
  save_epochs: 1
  save_model_name: "tmp"
  log_path: "logs"
